apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: demo-app
  labels:
    app: postgres
spec:
  # ClusterIP: Only reachable from inside the Kubernetes cluster
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: postgres
