apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: demo-app
type: Opaque
# stringData allows defining plaintext keys; Kubernetes automatically encodes them to base64
stringData:
  POSTGRES_DB: itemdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
