apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: demo-app
spec:
  # ReadWriteOnce: Can be mounted as read-write by a single node at a time
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # In Minikube, leaving storageClassName unset binds automatically to default 'standard' StorageClass
